[book]
authors = ["Chris Dornan"]
language = "en"
multilingual = false
src = "src"
title = "Polymede Benchmarks"


[output.html]

additional-css = ["theme/criterion.css"]
additional-js  = ["theme/criterion.js"]
